require: rubocop-performance

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.0
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'test/spec_helper.rb'
    - 'spec/factories/*'
    - 'vendor/**/*'
    - 'lib/tasks/display-coverage.rake'
    - 'loc_marc2bibframe2/**/*'

Lint/HandleExceptions:
  Enabled: false

Lint/UnreachableCode:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/models/ability.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'app/models/ability.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 27

Metrics/ParameterLists:
  Max: 6

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
