require:
 - rubocop-performance
 - rubocop-rails
 - rubocop-rspec
 - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'test/spec_helper.rb'
    - 'spec/factories/*'
    - 'vendor/**/*'
    - 'lib/tasks/display-coverage.rake'
    - 'loc_marc2bibframe2/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/BlockLength:
  Max: 101

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/models/ability.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'app/models/ability.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 27

Metrics/ParameterLists:
  Max: 6

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/edi_lin.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/package.rb'

RSpec/Capybara/SpecificMatcher:
  Exclude:
    - 'spec/features/*.rb'
    - 'spec/helpers/*.rb'
    - 'spec/views/**/*.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/rails_helper.rb'

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NoExpectationExample:
  Exclude:
    - 'spec/controllers/edi_lins_controller_spec.rb'
    - 'spec/models/shelf_sel_search_spec.rb'
    - 'spec/views/packages/new.html.erb_spec.rb'

RSpec/PendingWithoutReason:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
