# nodoc: Autogenerated
module ApplicationHelper
  def batch_menu_button
    link_to button_tag(
      'Batch upload menu',
      id: 'batch-menu-button',
      class: 'btn btn-md btn-default  btn-full'
    ), '/batch_record_updates'
  end

  def main_menu_button
    link_to button_tag(
      'Main menu',
      id: 'main-menu-button',
      class: 'btn btn-md btn-primary btn-full'
    ), root_path
  end
end
