# nodoc: Autogenerated
module ApplicationHelper
  def dialog_column_class
    'col-md-6 col-md-offset-3'
  end

  def label_column_class
    'col-sm-3'
  end

  def label_column_offset_class
    'col-sm-offset-3'
  end

  def content_column_class
    'col-sm-9'
  end

  def main_menu_button
    link_to button_tag(
      'Main menu'.html_safe,
      id: 'main-menu-button',
      class: 'btn btn-md btn-primary btn-full'
    ), root_path
  end
end
