symphony_cgi_url: 'https://example.com'
symphony_dataload_endowrpt: 'tmp/Dataload/EndowRpt'
symphony_config_digital_bookplates: 'spec/fixtures/files/symp_dor.txt'
symphony_dataload_digital_bookplates: 'tmp/Dataload/BookplateMerge/Batches/Queue'
lobbytrack_ips: ['171.1.1.1', '171.67.138.83']
# PL/SQL jobs
pl_sql_jobs:
  circ_stats_job:
    text: 'Run circ stats reports now'
    confirm: 'Circ stats reports started'
    command: 'circ_stats_rpt.daily_processing'
    sunet_ids:
      - 'nismoser'
      - 'jgreben'
      - 'dlrueda'
      - 'sdoljack'
      - 'mahmed'
  delphi_pay_test_job:
    text: 'Delphi payment test run'
    confirm: 'Delphi payment test run started'
    command: 'delphi_pay.test_run'
    sunet_ids:
      - 'kjochim'
      - 'jgreben'
      - 'dlrueda'
      - 'sdoljack'
      - 'mahmed'
