# nodoc: Autogenerated
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= begin
      user_id if user_id.present?
    end
  end
  helper_method :current_user

  def user_id
    request.env['REMOTE_USER'] || ENV['REMOTE_USER']
  end
end
