name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'
    - name: Install dependencies
      run: |
        bundle config set --local without 'production'
        bundle install
    - name: Set time zone for tests
      run: sudo timedatectl set-timezone America/Los_Angeles
    - name: Setup database
      run: |
        RAILS_ENV=test bundle exec rake db:test:prepare
    - name: Run tests
      run: |
        bundle exec rake spec
